import Container from "@/components/ui/container";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | Futures AI",
  description: "Legal disclaimer for Futures AI (AlphAi) crypto analytics platform.",
};

const content = {
  ko: {
    title: "면책 조항",
    lastUpdated: "최종 수정일: 2026년 3월 1일",
    importantNotice: "중요 고지",
    importantBody:
      "Futures AI (AlphAi)에서 제공하는 모든 정보, 분석, AI 시그널 및 콘텐츠는 일반적인 정보 제공 목적으로만 제공됩니다. 어떠한 경우에도 금융 투자 조언, 매매 권유 또는 추천으로 해석되어서는 안 됩니다.",
    sections: [
      {
        heading: "투자 조언이 아닙니다",
        body: `본 플랫폼은 투자 자문사, 금융 기관 또는 증권사가 아닙니다. 제공되는 AI 시그널, 차트 분석, 시장 데이터 및 뉴스는 정보 제공과 교육 목적으로만 제공되며, 특정 암호화폐의 매수, 매도 또는 보유를 권유하거나 추천하는 것이 아닙니다.`,
      },
      {
        heading: "AI 생성 콘텐츠",
        body: `본 서비스의 AI 기반 분석 및 시그널은 머신러닝 알고리즘에 의해 자동 생성됩니다. AI의 분석 결과는 부정확하거나 불완전할 수 있으며, 시장 상황의 급격한 변화를 반영하지 못할 수 있습니다. AI 생성 콘텐츠를 투자 결정의 유일한 근거로 사용해서는 안 됩니다.`,
      },
      {
        heading: "과거 성과와 미래 수익",
        body: `과거의 투자 성과, 시뮬레이션 결과 또는 백테스팅 데이터가 미래의 수익을 보장하지 않습니다. 암호화폐 시장은 극도로 변동성이 높으며, 투자 원금의 전부 또는 상당 부분을 잃을 수 있습니다.`,
      },
      {
        heading: "사용자 책임",
        body: `모든 투자 결정은 전적으로 사용자 본인의 판단과 책임 하에 이루어져야 합니다. 투자 전 반드시 자체적인 조사와 분석을 수행하고, 필요한 경우 공인된 금융 전문가의 조언을 구하시기 바랍니다. Futures AI는 사용자의 투자 결정이나 그로 인한 손실에 대해 어떠한 책임도 지지 않습니다.`,
      },
      {
        heading: "제3자 데이터 정확성",
        body: `본 서비스에서 표시되는 시세, 차트, 뉴스 등의 데이터는 CoinGecko, TradingView, 각종 뉴스 API 등 제3자 소스로부터 제공됩니다. 이러한 데이터의 정확성, 완전성 또는 적시성을 보장하지 않습니다. 데이터 지연, 오류 또는 누락이 발생할 수 있습니다.`,
      },
      {
        heading: "규제 관련",
        body: `암호화폐에 대한 규제는 국가 및 지역에 따라 다르며 지속적으로 변화하고 있습니다. 사용자는 해당 거주 지역의 법률 및 규정을 준수할 책임이 있습니다. 본 서비스는 법률 자문을 제공하지 않습니다.`,
      },
    ],
  },
  en: {
    title: "Disclaimer",
    lastUpdated: "Last updated: March 1, 2026",
    importantNotice: "Important Notice",
    importantBody:
      "All information, analysis, AI signals, and content provided by Futures AI (AlphAi) are for general informational purposes only. Under no circumstances should they be construed as financial investment advice, solicitation, or recommendation.",
    sections: [
      {
        heading: "Not Financial Advice",
        body: `This platform is not an investment advisor, financial institution, or brokerage. AI signals, chart analysis, market data, and news provided are for informational and educational purposes only and do not constitute a recommendation to buy, sell, or hold any cryptocurrency.`,
      },
      {
        heading: "AI-Generated Content",
        body: `AI-powered analysis and signals on this Service are automatically generated by machine learning algorithms. AI results may be inaccurate or incomplete and may not reflect rapid changes in market conditions. AI-generated content should not be used as the sole basis for investment decisions.`,
      },
      {
        heading: "Past Performance and Future Returns",
        body: `Past investment performance, simulation results, or backtesting data do not guarantee future returns. The cryptocurrency market is extremely volatile, and you may lose all or a significant portion of your investment.`,
      },
      {
        heading: "User Responsibility",
        body: `All investment decisions must be made at your own judgment and responsibility. Always conduct your own research and analysis before investing, and seek advice from a qualified financial professional if needed. Futures AI accepts no responsibility for your investment decisions or any resulting losses.`,
      },
      {
        heading: "Third-Party Data Accuracy",
        body: `Prices, charts, news, and other data displayed on this Service are sourced from third parties including CoinGecko, TradingView, and various news APIs. We do not guarantee the accuracy, completeness, or timeliness of this data. Data delays, errors, or omissions may occur.`,
      },
      {
        heading: "Regulatory Considerations",
        body: `Cryptocurrency regulations vary by country and jurisdiction and are continuously evolving. Users are responsible for complying with the laws and regulations of their respective jurisdictions. This Service does not provide legal advice.`,
      },
    ],
  },
};

export default function Disclaimer({
  params: { lang },
}: {
  params: { lang: string };
}) {
  const t = lang === "ko" ? content.ko : content.en;

  return (
    <div className="pt-20 pb-16 min-h-screen bg-zinc-950">
      <Container className="flex flex-col gap-8 py-10">
        <div className="flex flex-col gap-2">
          <h1 className="text-3xl sm:text-4xl font-bold text-white tracking-tight">
            {t.title}
          </h1>
          <p className="text-sm text-zinc-500 font-mono">{t.lastUpdated}</p>
        </div>

        {/* Important notice banner */}
        <div className="rounded-xl border border-amber-500/20 bg-amber-500/[0.05] p-6 flex flex-col gap-2">
          <h2 className="text-lg font-semibold text-amber-400">
            {t.importantNotice}
          </h2>
          <p className="text-sm leading-relaxed text-amber-200/80">
            {t.importantBody}
          </p>
        </div>

        <div className="flex flex-col gap-8">
          {t.sections.map((section) => (
            <section
              key={section.heading}
              className="flex flex-col gap-3 rounded-xl border border-white/[0.06] bg-white/[0.02] p-6"
            >
              <h2 className="text-lg font-semibold text-white">
                {section.heading}
              </h2>
              <p className="text-sm leading-relaxed text-zinc-400 whitespace-pre-line">
                {section.body}
              </p>
            </section>
          ))}
        </div>
      </Container>
    </div>
  );
}
